/** @format */

// export const GET_ROUNDS_DATA = "GET_ROUNDS_DATA";
// export const GET_ROUNDS_DATA_SUCCESS = "GET_ROUNDS_DATA_SUCCESS";
// export const GET_ROUNDS_DATA_ERROR = "GET_ROUNDS_DATA_ERROR";

export const WALLET_CONNECT_REQUEST = "WALLET_CONNECT_REQUEST"
export const WALLET_CONNECT_REQUEST_SUCCESS = "WALLET_CONNECT_REQUEST_SUCCESS"
export const WALLET_CONNECT_REQUEST_ERROR = "WALLET_CONNECT_REQUEST_ERROR"

export const PORTFOLIO_DATA_REQUEST = "PORTFOLIO_DATA_REQUEST_ERROR"
export const PORTFOLIO_DATA_REQUEST_SUCCESS = "PORTFOLIO_DATA_REQUEST_SUCCESS"
export const PORTFOLIO_DATA_REQUEST_ERROR = "PORTFOLIO_DATA_REQUEST_ERROR"

export const SELECTED_PLANS = "SELECTED_PLANS"
//invoice reducer
export const INVOICE_ADDING = "INVOICE_ADDING"

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE"
//CollectionApi Actions
export const USERS_LOAD_START = "USERS_LOAD_START"
export const USERS_LOAD_SUCCESS = "USERS_LOAD_SUCCESS"
export const USERS_LOAD_ERROR = "USERS_LOAD_ERROR"
export const GET_COLLECTIONS = "GET_COLLECTIONS"
export const GET_TRASACTION_DATA = "GET_TRASACTION_DATA"

// Txn api data
export const TXN_LOAD_START = "TXN_LOAD_START"
export const TXN_LOAD_SUCCESS = "TXN_LOAD_SUCCESS"
export const TXN_LOAD_ERROR = "TXN_LOAD_ERROR"
//nft api data
export const NFT_LOAD_START = "NFT_LOAD_START"
export const NFT_LOAD_SUCCESS = "NFT_LOAD_SUCCESS"
export const NFT_LOAD_ERROR = "NFT_LOAD_ERROR"